Create Low VOC
EarthSciML/AerosolMTK.jl pull request #2
Opened 2021-12-09 19:42 UTC by ss144-illinois

2021-12-09 20:10 UTC, ctessum commented on src/Low VOC
> +	for n in 1:size(Tp,1), j in 1:size(Tp,2)
In this for loop, you are creating indexes `n` and `j`, but you don't ever use them—instead you use a broadcast operation in the equation below, so you don't really need a for loop. This is in general fine but in this case the way that it is working is that the first result is based on T = 263.61; p=0.23, the second result is based on T=267.98; p=0.40, and so on. What you probably want is to have results based on all of the combinations of T and p.

To do this you might just be able to take the transpose (or adjoint) of one of the vectors. For example, you could try replacing `Tp[:, 2]` with `Tp[:,2]'`.

The end result that we would want would be a matrix of Kom values here, then you could plot it using a heatmap where the rows are different temperatures and the columns are different pressures, or something like that.

2021-12-09 20:10 UTC, ctessum commented on src/Low VOC
> +T = [263.61, 267.98, 273.16, 278.22, 283.14, 288.01, 293.24, 293.25, 298.26, 303.29, 308.17, 313.24, 318.21, 323.14, 328.24, 333.39, 338.10, 343.06] #temperature range
What are the units of T and p?

2021-12-09 20:11 UTC, ctessum commented on src/Low VOC
> +p = [0.23, 0.40, 0.74, 1.38, 2.41, 4.13, 6.93, 6.95, 11.35, 18.45, 28.95, 44.73, 68.82, 104.14, 158.41, 237.54, 340.76, 488.58] #vapor pressure
p is the vapor pressure, but what is it the vapor pressure of? Please add some more detail.

2021-12-09 20:13 UTC, ctessum commented on src/Low VOC
> +plot(Kₒₘ, temp, c=:blue, lab = :none, xlabel="Kₒₘ", ylabel="1/Temperature")
Can you add some text here describing what this plot is telling us? In what ways to the results here agree or disagree with what you would expect based on your knowledge of air pollution? Does these results match the results in the paper?

It would also be good to create plots of multiple chemicals here and compare how they are similar and different

2021-12-09 20:15 UTC, ctessum commented on src/Low VOC
> +
Could you add a comment here containing a paragraph or two describing what this code does? What is it a model of? What paper does it come from? What other information would someone need to understand what you've done here, or to use this code in their own work?

2021-12-09 20:35 UTC, ctessum commented
Also, you can review the contributor license agreement above, and if you agree with it, just type "I have reviewed and hereby sign the CLA" in the comment box below. It just basically just says that you agree that we can release your work as open source software.

2021-12-17 18:54 UTC, ss144-illinois commented
I have reviewed and hereby sign the CLA

2021-12-17 22:35 UTC, ss144-illinois commented
I have reviewed and hereby sign the CLA

2021-12-20 17:55 UTC, ctessum requested changes

2021-12-20 17:55 UTC, ctessum commented on src/Low VOC
> +	C_sat = df[:,4] #units saturation concentration
There are a number of references to `df` in this file, but `df` isn't defined anywhere, so the code doesn't run.

2021-12-20 17:55 UTC, ctessum commented on src/Low VOC
> +
Need to also add `using Markdown` here

2021-12-22 20:54 UTC, ctessum approved these changes

2021-12-22 21:03 UTC, merged